### ISSUE TITLE
faild to build on heroku 

### ISSUE THREAD

**Issue by kikandychan** [muhammedfurkan/Spotify-Telegram-Bio-Updater#6]
The log is in the below.
-----> Building on the Heroku-22 stack
-----> Using buildpack: heroku/python
-----> Python app detected
-----> Using Python version specified in runtime.txt
 !     Requested runtime 'python-3.10.2' is not available for this stack (heroku-22).
 !     For supported versions, see: https://devcenter.heroku.com/articles/python-support
 !     Push rejected, failed to compile Python app.
 !     Push failed
Could you please tell me what wrong is with it

**Comment by muhammedfurkan** [comment]
> The log is in the below. -----> Building on the Heroku-22 stack -----> Using buildpack: heroku/python -----> Python app detected -----> Using Python version specified in runtime.txt ! Requested runtime 'python-3.10.2' is not available for this stack (heroku-22). ! For supported versions, see: https://devcenter.heroku.com/articles/python-support ! Push rejected, failed to compile Python app. ! Push failed Could you please tell me what wrong is with it

I updated. Check it again, please.

**Comment by kikandychan** [comment]
hmmm. I'm sorry but now it shows
-----> Building on the Heroku-22 stack
-----> Using buildpack: heroku/python
-----> Python app detected
-----> Using Python version specified in runtime.txt
 !     
 !     A Python security update is available! Upgrade as soon as possible to: python-3.10.8
 !     See: https://devcenter.heroku.com/articles/python-runtimes
 !     
-----> Installing python-3.10.6
-----> Installing pip 22.2.2, setuptools 63.4.3 and wheel 0.37.1
-----> Installing SQLite3
-----> Installing requirements with pip
       Collecting telethon
         Downloading Telethon-1.25.4-py3-none-any.whl (569 kB)
       Collecting pyaesni
         Downloading pyaesni-0.16.tar.gz (2.7 kB)
         Preparing metadata (setup.py): started
         Preparing metadata (setup.py): finished with status 'done'
       Collecting telethon-tgcrypto
         Downloading telethon_tgcrypto-0.0.3-py3-none-any.whl (2.7 kB)
       Collecting requests
         Downloading requests-2.28.1-py3-none-any.whl (62 kB)
       Collecting rsa
         Downloading rsa-4.9-py3-none-any.whl (34 kB)
       Collecting pyaes
         Downloading pyaes-1.6.1.tar.gz (28 kB)
         Preparing metadata (setup.py): started
         Preparing metadata (setup.py): finished with status 'done'
       Collecting tgcrypto
         Downloading TgCrypto-1.2.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (59 kB)
       Collecting idna<4,>=2.5
         Downloading idna-3.4-py3-none-any.whl (61 kB)
       Collecting certifi>=2017.4.17
         Downloading certifi-2022.9.24-py3-none-any.whl (161 kB)
       Collecting urllib3<1.27,>=1.21.1
         Downloading urllib3-1.26.12-py2.py3-none-any.whl (140 kB)
       Collecting charset-normalizer<3,>=2
         Downloading charset_normalizer-2.1.1-py3-none-any.whl (39 kB)
       Collecting pyasn1>=0.1.3
         Downloading pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
       Building wheels for collected packages: pyaesni, pyaes
         Building wheel for pyaesni (setup.py): started
         Building wheel for pyaesni (setup.py): finished with status 'error'
         error: subprocess-exited-with-error
         
         × python setup.py bdist_wheel did not run successfully.
         │ exit code: 1
         ╰─> [49 lines of output]
             running bdist_wheel
             running build
             running build_ext
             CMake Error: The source directory "/tmp/pip-install-2pm6f69z/pyaesni_58efe335d0c5441298b38b967ee24674" does not appear to contain CMakeLists.txt.
             Specify --help for usage, or press the help button on the CMake GUI.
             Traceback (most recent call last):
               File "<string>", line 2, in <module>
               File "<pip-setuptools-caller>", line 34, in <module>
               File "/tmp/pip-install-2pm6f69z/pyaesni_58efe335d0c5441298b38b967ee24674/setup.py", line 83, in <module>
                 setup(
               File "/app/.heroku/python/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
                 return distutils.core.setup(**attrs)
               File "/app/.heroku/python/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
                 return run_commands(dist)
               File "/app/.heroku/python/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
                 dist.run_commands()
               File "/app/.heroku/python/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_commands
                 self.run_command(cmd)
               File "/app/.heroku/python/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
                 super().run_command(command)
               File "/app/.heroku/python/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
                 cmd_obj.run()
               File "/app/.heroku/python/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 299, in run
                 self.run_command('build')
               File "/app/.heroku/python/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
                 self.distribution.run_command(command)
               File "/app/.heroku/python/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
                 super().run_command(command)
               File "/app/.heroku/python/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
                 cmd_obj.run()
               File "/app/.heroku/python/lib/python3.10/site-packages/setuptools/command/build.py", line 24, in run
                 super().run()
               File "/app/.heroku/python/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 132, in run
                 self.run_command(cmd_name)
               File "/app/.heroku/python/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
                 self.distribution.run_command(command)
               File "/app/.heroku/python/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
                 super().run_command(command)
               File "/app/.heroku/python/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
                 cmd_obj.run()
               File "/app/.heroku/python/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 79, in run
                 _build_ext.run(self)
               File "/app/.heroku/python/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
                 self.build_extensions()
               File "/tmp/pip-install-2pm6f69z/pyaesni_58efe335d0c5441298b38b967ee24674/setup.py", line 54, in build_extensions
                 subprocess.check_call(['cmake',
               File "/app/.heroku/python/lib/python3.10/subprocess.py", line 369, in check_call
                 raise CalledProcessError(retcode, cmd)
             subprocess.CalledProcessError: Command '['cmake', '-S', '/tmp/pip-install-2pm6f69z/pyaesni_58efe335d0c5441298b38b967ee24674', '-B', 'pyaesni_build', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_ASM_NASM_COMPILER=yasm', '-DPython_INCLUDE_DIR=/app/.heroku/python/include/python3.10', '-DPython_LIBRARY=/app/.heroku/python/lib/libpython3.10.so', '-DCMAKE_INSTALL_PREFIX=/tmp/pip-install-2pm6f69z/pyaesni_58efe335d0c5441298b38b967ee24674/build/temp.linux-x86_64-cpython-310/install', '-DPYTHON_VERSION=3.10.6']' returned non-zero exit status 1.
             [end of output]
         
         note: This error originates from a subprocess, and is likely not a problem with pip.
         ERROR: Failed building wheel for pyaesni
         Running setup.py clean for pyaesni
         Building wheel for pyaes (setup.py): started
         Building wheel for pyaes (setup.py): finished with status 'done'
         Created wheel for pyaes: filename=pyaes-1.6.1-py3-none-any.whl size=26347 sha256=8572f91803651415321fa3a377d81170a5aa46a13d7cc3a5391be111fa9a8114
         Stored in directory: /tmp/pip-ephem-wheel-cache-rzkees1m/wheels/d6/84/5f/ea6aef85a93c7e1922486369874f4740a5642d261e09c59140
       Successfully built pyaes
       Failed to build pyaesni
       Installing collected packages: pyasn1, pyaes, urllib3, tgcrypto, rsa, pyaesni, idna, charset-normalizer, certifi, telethon-tgcrypto, telethon, requests
         Running setup.py install for pyaesni: started
         Running setup.py install for pyaesni: finished with status 'error'
         error: subprocess-exited-with-error
         
         × Running setup.py install for pyaesni did not run successfully.
         │ exit code: 1
         ╰─> [53 lines of output]
             running install
             /app/.heroku/python/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
               warnings.warn(
             running build
             running build_ext
             CMake Error: The source directory "/tmp/pip-install-2pm6f69z/pyaesni_58efe335d0c5441298b38b967ee24674" does not appear to contain CMakeLists.txt.
             Specify --help for usage, or press the help button on the CMake GUI.
             Traceback (most recent call last):
               File "<string>", line 2, in <module>
               File "<pip-setuptools-caller>", line 34, in <module>
               File "/tmp/pip-install-2pm6f69z/pyaesni_58efe335d0c5441298b38b967ee24674/setup.py", line 83, in <module>
                 setup(
               File "/app/.heroku/python/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
                 return distutils.core.setup(**attrs)
               File "/app/.heroku/python/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
                 return run_commands(dist)
               File "/app/.heroku/python/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
                 dist.run_commands()
               File "/app/.heroku/python/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_commands
                 self.run_command(cmd)
               File "/app/.heroku/python/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
                 super().run_command(command)
               File "/app/.heroku/python/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
                 cmd_obj.run()
               File "/app/.heroku/python/lib/python3.10/site-packages/setuptools/command/install.py", line 68, in run
                 return orig.install.run(self)
               File "/app/.heroku/python/lib/python3.10/site-packages/setuptools/_distutils/command/install.py", line 698, in run
                 self.run_command('build')
               File "/app/.heroku/python/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
                 self.distribution.run_command(command)
               File "/app/.heroku/python/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
                 super().run_command(command)
               File "/app/.heroku/python/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
                 cmd_obj.run()
               File "/app/.heroku/python/lib/python3.10/site-packages/setuptools/command/build.py", line 24, in run
                 super().run()
               File "/app/.heroku/python/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 132, in run
                 self.run_command(cmd_name)
               File "/app/.heroku/python/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
                 self.distribution.run_command(command)
               File "/app/.heroku/python/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
                 super().run_command(command)
               File "/app/.heroku/python/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
                 cmd_obj.run()
               File "/app/.heroku/python/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 79, in run
                 _build_ext.run(self)
               File "/app/.heroku/python/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
                 self.build_extensions()
               File "/tmp/pip-install-2pm6f69z/pyaesni_58efe335d0c5441298b38b967ee24674/setup.py", line 54, in build_extensions
                 subprocess.check_call(['cmake',
               File "/app/.heroku/python/lib/python3.10/subprocess.py", line 369, in check_call
                 raise CalledProcessError(retcode, cmd)
             subprocess.CalledProcessError: Command '['cmake', '-S', '/tmp/pip-install-2pm6f69z/pyaesni_58efe335d0c5441298b38b967ee24674', '-B', 'pyaesni_build', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_ASM_NASM_COMPILER=yasm', '-DPython_INCLUDE_DIR=/app/.heroku/python/include/python3.10', '-DPython_LIBRARY=/app/.heroku/python/lib/libpython3.10.so', '-DCMAKE_INSTALL_PREFIX=/tmp/pip-install-2pm6f69z/pyaesni_58efe335d0c5441298b38b967ee24674/build/temp.linux-x86_64-cpython-310/install', '-DPYTHON_VERSION=3.10.6']' returned non-zero exit status 1.
             [end of output]
         
         note: This error originates from a subprocess, and is likely not a problem with pip.
       error: legacy-install-failure
       
       × Encountered error while trying to install package.
       ╰─> pyaesni
       
       note: This is an issue with the package mentioned above, not pip.
       hint: See above for output from the failure.
 !     Push rejected, failed to compile Python app.
 !     Push failed

**Comment by muhammedfurkan** [comment]
I edited it again. Sorry for the error.

**Comment by kikandychan** [comment]
sorry dude. it failed again. And when I continued, I seemly reached the limits. Now it shows Your account has reached its concurrent builds limit.
